title: marcvd
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "unnamed"
      author: "Marc Volker Dickmann"
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
paginate_path: /page:num
paginate: 10
