title: marcvd
paginate: 10

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "unnamed"
      author: "Marc Volker Dickmann"
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
